### ISSUE TITLE
Empty brackets

### ISSUE THREAD

**Issue by alexreg** [alex-ball/bathbib#10] opened 2021-01-21 19:10 UTC
Here is the relevant entry from my Biber (`.bib`) file.

```bibtex
@article{Auffeves_Grangier_2015,
	title     = {Classical selection and quantum {D}arwinism},
	volume    = {68},
	issn      = {1945-0699},
	doi       = {10.1063/pt.3.2759},
	number    = {5},
	journal   = {{Physics Today}},
	publisher = {{AIP Publishing}},
	author    = {Auffèves, Alexia and Grangier, Philippe},
	date      = {2015-05-01},
	pages     = {8-8},
}
```

This renders as such using the default biblatex-bath settings:

<img width="668" alt="Screenshot 2021-01-21 at 19 08 31" src="https://user-images.githubusercontent.com/67036/105399835-0ead2500-5c1c-11eb-9828-13197c5c84a2.png">

The empty brackets after the volume and issue number are not desirable. I believe they are for the `issue` field, but I am (correctly, as I understand) using the numerical `number` field instead.

Is this a bug in biblatex-bath, or should I be using a certain setting? (Note, some of my entries will have `volume`, `number`, *and* `issue` fields, and I suppose all should be displayed in this case still.)

P.S. Thanks for your great work on creating this style.

**Comment by alex-ball** [comment] 2021-01-21 20:17
Duplicate of #9. Please use one of the solutions there (or compile from the latest source) until the next release.

**Closed as completed by alex-ball** 2021-01-21 20:17 UTC
Labels: duplicate

**Comment by alexreg** [comment] 2021-01-21 20:49
Sorry, I didn't notice because the issue was already closed. Appreciate the workaround.
